name: Run oscillator-overlap experiments
on:
  push:
    branches:
      - use-github-actions-for-diss-cases

jobs:
  get_gh_context:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./oscillator-overlap
    container: precice/precice:nightly
    steps:
      - name: Print gh context from python
        run: |
          python3 print_gh_context.py
  # run_experiments:
  #   name: Run oscillator-overlap
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./oscillator-overlap
  #   container: precice/precice:nightly
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #     - name: Install Dependencies
  #       run: |
  #         apt-get -qq update
  #         apt-get -qq install software-properties-common python3-dev python3-pip python3.12-venv git apt-utils pkg-config
  #         rm -rf /var/lib/apt/lists/*
  #     - name: Create venv
  #       run: |
  #         ./make-venv.sh
  #     - name: Activate venv
  #       # see https://stackoverflow.com/a/74669486
  #       run: |
  #         . .venv/bin/activate
  #         echo PATH=$PATH >> $GITHUB_ENV
  #     - name: Run tutorial
  #       run: |
  #         ./convergence_study.sh
  #     - name: Store results
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: results
  #         path: |
  #           convergence-studies
      