name: Run perpendicular-flap experiments
on:
  push:
    branches:
      - use-github-actions-for-diss-cases

jobs:
  run_experiments:
    strategy:
      matrix:
        experiment:
        - name: Figure 6.6
          args: 'fig6_6_config.csv -o studies/fig6_6.csv'
        - name: Figure 6.7
          args: 'fig6_7_config.csv -o studies/fig6_7.csv'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./perpendicular-flap
    container: benjaminrodenberg/fenics-openfoam
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev python3-pip python3.12-venv
          apt-get -qq install git apt-utils pkg-config 
          apt-get -qq install sudo curl tmux
          rm -rf /var/lib/apt/lists/*
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - name: Create venv
        run: |
          ./make-venv.sh
      - name: Activate main venv # see https://stackoverflow.com/a/74669486
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Try jinja2
        run: python3 -c "import jinja2"
      - name: Activate OpenFOAM # From https://github.com/gerlero/setup-openfoam/blob/68e0bf96c7f2aac1a100291a5d61fff934a472a8/action.yml#L54-L69
        run: |
          old_path="$PATH"
          source /usr/lib/openfoam/openfoam2412/etc/bashrc || true

          for var in "${!WM_@}"; do
            echo "$var=${!var}" >> "$GITHUB_ENV"
          done

          for var in "${!FOAM_@}"; do
            echo "$var=${!var}" >> "$GITHUB_ENV"
          done

          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

          echo "${PATH/%:$old_path}" >> "$GITHUB_PATH"
      # - name: Try blockMesh
      #   run: blockMesh
      # - name: Try jinja2
      #   run: python3 -c "import jinja2"
  merge:
    runs-on: ubuntu-latest
    needs: run_experiments
    steps:
      - name: Merge results
        uses: actions/upload-artifact/merge@v4
        with:
          name: perpendicular-flap
